### ISSUE TITLE
Button text inconsistancies

### ISSUE THREAD

**Issue by geeksnglitter** [CenterForOpenScience/osf-style#69]
## Steps
1. Go to the settings page.
2. See that some buttons are sentence case and some are title case.

![screen shot 2015-07-28 at 8 59 33 am](https://cloud.githubusercontent.com/assets/7839433/8932023/6c9628a6-3508-11e5-8916-c16c4d00a5ec.png) ![screen shot 2015-07-28 at 8 59 41 am](https://cloud.githubusercontent.com/assets/7839433/8932025/6e141486-3508-11e5-8d47-f919e232d79a.png)

## Expected
All buttons would have the same case.

## Reality
Currently buttons have inconsistent cases and there is no explicit rule in the style guide.

Originally I believed that buttons should be title case (currently most of our buttons are), but @sloria brought up some good points here: https://github.com/CenterForOpenScience/osf.io/pull/3830#issuecomment-125313280

And here is another discussion of this issue: http://ux.stackexchange.com/questions/28297/should-we-use-title-case-or-sentence-case-for-headlines-and-buttons
 
Should buttons be title or sentence case?
I believe most other button text issues are already handled in the style guide, but if there are any comments on that feel free to bring them up here!

**Comment by geeksnglitter** [comment]
@natasharichter, @caileyfitz, @lbanner :)

**Comment by caileyfitz** [comment]
@geeksnglitter Hm... This is tricky. I definitely agree that the case should be consistent, whether it is title case or sentence case. I think that sentence case is the more acceptable usage here (mostly because that's what GitHub and Dropbox do), so I vote for sentence case. It can also sometimes be hard to know what needs to be capitalized in title case, so sentence casing all buttons removes that extra difficulty.

**Comment by NatashaRichter** [comment]
@geeksnglitter I agree with @caileyfitz. I like sentence case in buttons. Her reasons stated above are good. We'll also need to think about links. In some cases, links are all lower case and some cases sentence case, but I can create a separate issue for that.

**Comment by geeksnglitter** [comment]
Side note: Google's main buttons are title case.
![screen shot 2015-07-28 at 10 44 30 am](https://cloud.githubusercontent.com/assets/7839433/8934486/db05af70-3515-11e5-9e2c-4ac24431a6b5.png)

We can follow github's lead and make buttons sentence case, but that means we should probably change a lot of other things on the OSF to be sentence case, such as the links Natasha mentioned. I will make another issue about general site capitalization soon.

**Comment by caneruguz** [comment]
Well @sloria is bringing up examples but they are not indicative of convention I think, there still seems to be discussion on that topic. However his solution is something I would support as well. 

When we can we should try to justify these decisions with some good use reasons. The most compelling I have heard in these discussions so far is that "Sentence case" allows for better readibility since the capitalization continues as single case and does not need to be interpreted as separation of words.  Title case does not seem to have an overwhelming advantage and may create more questions as stated here. 

I vote we do sentence case and move on to make this a rule for Buttons and stand alone links. Links within sentences should follow whatever that sentence structure is.

**Comment by caneruguz** [comment]
Closing as part of this issue: https://github.com/CenterForOpenScience/osf-style/issues/71
